**Part 1. Data Analysis and Bayes Nets**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Naive Bayes classifier**

In [3]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# Load the data
X = np.load('/content/drive/MyDrive/Data/smiley_dataset/smiley_X.npy')
y = np.load('/content/drive/MyDrive/Data/smiley_dataset/smiley_Y.npy')

# Split the data into training and testing sets
split_idx = int(0.8 * len(X))
X_train, y_train = X[:split_idx], y[:split_idx]
X_test, y_test = X[split_idx:], y[split_idx:]

# Create a Naive Bayes classifier
clf = GaussianNB()

# Fit the classifier on the training data
clf.fit(X_train.reshape(-1, 81), y_train)

# Use the classifier to make predictions on the test data
y_pred = clf.predict(X_test.reshape(-1, 81))
y_prob = clf.predict_proba(X_test.reshape(-1, 81))

# Normalize the target scores to ensure they sum up to 1.0 over classes
y_prob_norm = y_prob / np.sum(y_prob, axis=1, keepdims=True)

# Calculate the evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
# roc_auc = roc_auc_score(y_test, y_prob_norm, multi_class='ovo')
confusion = confusion_matrix(y_test, y_pred)

# Print the evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 score: {f1}")
# print(f"ROC AUC score: {roc_auc}")
print(f"Confusion matrix:\n{confusion}")


Accuracy: 0.7317073170731707
Precision: 0.8223577235772358
Recall: 0.7317073170731707
F1 score: 0.7652321310857897
Confusion matrix:
[[17  7  0]
 [ 1 13  3]
 [ 0  0  0]]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
